<?php
return array(
	'articles' => array (
		'_data' => array(
		    'up' => array(
		        'insert' => array(
                    array('id' => 2, 'template_id' => 3, 'title' => 'Harry Potter and the Philosopher\'s Stone', 'url' => 'Harry_Potter_and_the_Philosophers_Stone', 'summary' => 'Harry Potter and the Philosopher\'s Stone is the first novel in the Harry Potter series written by J. K. Rowling and featuring Harry Potter, a young wizard. It describes how Harry discovers he is a wizard, makes close friends and a few enemies at the Hogwarts School of Witchcraft and Wizardry, and with the help of his friends thwarts an attempted comeback by the evil wizard Lord Voldemort, who killed Harry\'s parents when Harry was one year old.
                    
The book, which is J.K. Rowling\'s debut novel, was published on 26 June 1997 by Bloomsbury in London. In 1998 Scholastic Corporation published an edition for the United States market under the title Harry Potter and the Sorcerer\'s Stone. The novel won most of the British book awards that were judged by children, and other awards in the US. The book reached the top of the New York Times list of best-selling fiction in August 1999, and stayed near the top of that list for much of 1999 and 2000. It has been translated into several other languages and has been made into a feature-length film of the same name.', 'summary_html' => 'Harry Potter and the Philosopher\'s Stone is the first novel in the Harry Potter series written by J. K. Rowling and featuring Harry Potter, a young wizard. It describes how Harry discovers he is a wizard, makes close friends and a few enemies at the Hogwarts School of Witchcraft and Wizardry, and with the help of his friends thwarts an attempted comeback by the evil wizard Lord Voldemort, who killed Harry\'s parents when Harry was one year old.<br /><br />The book, which is J.K. Rowling\'s debut novel, was published on 26 June 1997 by Bloomsbury in London. In 1998 Scholastic Corporation published an edition for the United States market under the title Harry Potter and the Sorcerer\'s Stone. The novel won most of the British book awards that were judged by children, and other awards in the US. The book reached the top of the New York Times list of best-selling fiction in August 1999, and stayed near the top of that list for much of 1999 and 2000. It has been translated into several other languages and has been made into a feature-length film of the same name.<br />'),
                ),
		    ),
		),
	),

	'articleSections' => array (
		'_data' => array(
		    'up' => array(
		        'insert' => array(
                    array('article_id' => 2, 'section_id' => 8, 'raw' => 'Before the start of the novel, Voldemort, considered the most evil and powerful dark wizard in history, kills Harry\'s parents but mysteriously vanishes after trying to kill the infant Harry. While the wizarding world celebrates Voldemort\'s downfall, Professor Dumbledore, Professor McGonagall and Rubeus Hagrid place the one year-old orphan in the care of his neglectful and abusive Muggle (non-wizard) uncle and aunt: Vernon and Petunia Dursley, who have a son, Dudley, a spoiled and selfish boy.

For ten years, Harry is tormented by the Dursleys. Shortly before his eleventh birthday, a series of letters addressed to Harry arrive, but Vernon destroys them before Harry can read them, leading only to an influx of more letters. To get away from the letters, Vernon takes the family to a small island. As they are settling in, Hagrid bursts through the door to tell Harry what the Dursleys have kept from him: Harry is a wizard and has been accepted at Hogwarts.

Hagrid takes Harry to Diagon Alley, a magically concealed shopping precinct in London, where Harry is bewildered to discover how famous he is among wizards as "the boy who lived." He also finds that he is quite wealthy, since a bequest from his parents has remained on deposit at Gringotts Wizarding Bank. Guided by Hagrid, he buys the equipment he needs for Hogwarts. At the wand shop, he finds that the wand that suits him best is the twin of Voldemort\'s; both wands contain feathers from the same phoenix.[1]

A month later, Harry leaves the Dursleys\' home to catch the Hogwarts Express from King\'s Cross railway station. There he meets the Weasley family, who show him how to pass through the magical wall to Platform 9¾, where the train is waiting. While on the train, Harry makes friends with Ron Weasley, who tells him that someone tried to rob a vault at Gringotts. During the ride, they meet Hermione Granger. Another new pupil, Draco Malfoy, accompanied by his sidekicks Vincent Crabbe and Gregory Goyle, offers to advise Harry, but Harry dislikes Draco\'s arrogance and prejudice.

Before the term\'s first dinner in the school\'s Great Hall, the new pupils are allocated to houses by the Sorting Hat. Before it is Harry\'s turn, he catches Professor Snape\'s eye and feels a pain in the scar Voldemort left on his forehead. While Harry is being sorted, the Hat wonders whether he should be in Slytherin, but when Harry objects, the Hat sends him to Gryffindor.

After a terrible first Potions lesson with Snape, Harry and Ron visit Hagrid, who lives in a cabin on the edge of the Forbidden Forest. There they learn that the attempted robbery at Gringotts happened the day Harry withdrew money. Harry remembers that Hagrid had removed a small package from the vault that had been broken into.

During the new pupils\' first broom-flying lesson, Neville Longbottom breaks his wrist, and Draco takes advantage to throw the forgetful Neville\'s fragile Remembrall high in the air. Harry gives chase on his broomstick, catching the Remembrall inches from the ground. Professor McGonagall dashes out and appoints him as the new Seeker for the Gryffindor Quidditch team.[2]

When Draco tricks Ron and Harry, accompanied by Neville and Hermione Granger, into a midnight excursion, they accidentally enter a forbidden corridor and find a huge three-headed dog. The group hastily retreats, and Hermione notices that the dog is standing over a trap-door. Harry concludes that the monster is guarding the package Hagrid retrieved from Gringotts.

After Ron criticises Hermione\'s ostentatious proficiency in Charms, she hides in the girls\' toilet, crying. At the Halloween Night dinner, Professor Quirrell reports that a troll has entered the dungeons. While everyone returns to their dormitories, Harry and Ron rush to warn Hermione. The troll corners Hermione in the toilet but Harry and Rone clumsily save her. Afterwards, Hermione takes the blame for the battle and becomes a firm friend of the two boys.

The evening before Harry\'s first Quidditch match, he sees Snape receiving medical attention from Filch for a bite on his leg caused by the three-headed dog. During the game, Harry\'s broomstick goes out of control, endangering his life, and Hermione notices that Snape is staring at Harry and muttering. She dashes over to the Professors\' stand, knocking over Professor Quirrell in her haste, and sets fire to Snape\'s robe. Harry regains control of his broomstick and catches the Golden Snitch, winning the game for Gryffindor. Hagrid refuses to believe that Snape was responsible for Harry\'s danger, but lets slip that he bought the three-headed dog and that the monster is guarding a secret that belongs to Professor Dumbledore and someone called Nicolas Flamel.

Harry and the Weasleys stay at Hogwarts for Christmas, and one of Harry\'s presents, from an anonymous donor, is an Invisibility Cloak owned by his father. Harry uses the Cloak to search the library\'s Restricted Section for information about the mysterious Flamel, and he happens to find a room containing the Mirror of Erised, which shows him his parents and several of their ancestors. Harry becomes addicted to the Mirror\'s visions until he is rescued by Professor Dumbledore, who explains that it only shows the viewer what it most desperately longs for.

When the rest of the pupils return for the next term, Draco plays a prank on Neville, and Harry consoles Neville with a sweet. The collectible card wrapped with the sweet identifies Flamel as an alchemist. Hermione soon finds that he is a 665-year-old man who possesses the only known Philosopher\'s Stone, from which an elixir of life can be extracted. A few days later, Harry notices Snape sneaking towards the outskirts of the Forbidden Forest. There he half-hears a furtive conversation about the Philosopher\'s Stone between Snape and Quirrell. Harry concludes that Snape is trying to steal the Stone and Quirrell has helped prepare a series of defences for it, which was an almost fatal mistake.

The three friends discover that Hagrid is raising a baby dragon, which is against wizard law, and arrange to smuggle it out of the country around midnight. Draco, hoping to get them into trouble, tells Professor McGonagall. Although the dragon is safely away, they are caught outside of their dormitory. Harry, Hermione, Draco, and Neville (who, trying to stop Harry and Hermione after hearing what Draco had been saying, was caught by McGonagall as well) are punished by helping Hagrid to rescue a badly injured unicorn in the Forbidden Forest. They split into two parties, and Harry and Draco find the unicorn dead, surrounded by its blood. A hooded figure crawls to the corpse and drinks the blood, then moves towards Harry, who is knocked out by an agonising pain in his scar. When Harry regains consciousness, the hooded figure is gone and a centaur, Firenze, offers to give him a ride back to the school. The centaur tells Harry that drinking a unicorn\'s blood will save the life of a mortally injured person, but at the price of having a cursed life from that moment on. Firenze suggests Voldemort drank the unicorn\'s blood to gain enough strength to make the elixir of life from the Philosopher\'s Stone, and regain full health by drinking that.

A few weeks later, Harry learns from Hagrid that the dragon egg was given to him by a hooded stranger who had asked him how to get past the three-headed dog, which Hagrid had admitted was easy – music sends it to sleep. Realising that one of the Philosopher\'s Stone\'s defences is no longer secure, Harry goes to inform Professor Dumbledore, only to find that the headmaster has just left for a meeting in London. Harry concludes that Snape faked the message that called Dumbledore away and will try to steal the Stone that night.

Covered by the Invisibility Cloak, Harry and his two friends go to the three-headed dog\'s chamber, where Harry sends the beast to sleep by playing a flute. After lifting the trap-door, they encounter a series of obstacles, each of which requires special skills possessed by one of the three, and one of which requires Ron to sacrifice himself in a game of wizard\'s chess. In the final room Harry, now alone, finds Quirrell rather than Snape. Quirrell admits that he let in the troll and that he tried to kill Harry during the first Quidditch match. Snape had been trying to protect Harry all along. Quirrell serves Voldemort and, after failing to steal the Philosopher\'s Stone from Gringotts, allowed his master to possess him in order to improve their chances of success. However, the only other object in the room is the Mirror of Erised, and Quirrell can see no sign of the Stone. At Voldemort\'s bidding, Quirrell forces Harry to stand in front of the Mirror. Harry feels the Stone drop into his pocket and tries to stall. Quirrell removes his turban, revealing the face of Voldemort on the back of his head. Voldemort/Quirrell tries to grab the Stone from Harry, but simply touching Harry causes Quirrell\'s flesh to burn. After further struggles, Harry passes out.

He awakes in the school hospital, where Professor Dumbledore tells him that he survived because his mother sacrificed her life to protect him, and Voldemort could not understand the power of such love. Voldemort left Quirrell to die and is likely to return by some other means. The Stone has now been destroyed.

Harry returns to the Dursleys for the summer holiday, but does not tell them that under-age wizards are forbidden to use magic outside Hogwarts.', 'html' => ''),
                ),
		    ),
		),
	),

);