#!/usr/bin/env bash
set -e

node wikipedia.js --parent "Franchises" --title "Star Trek" --out "./data/wiki/star_trek.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: The Original Series" --out "./data/wiki/st_tos.json"
node wikipedia.js --parent "Star Trek: The Original Series" --title "James T. Kirk" --out "./data/wiki/st_kirk.json"
node wikipedia.js --parent "Star Trek: The Original Series" --title "Spock" --out "./data/wiki/st_spock.json"
node wikipedia.js --parent "Star Trek: The Original Series" --title "Scotty (Star Trek)" --rename "Montgomery \"Scotty\" Scott" --out "./data/wiki/st_scotty.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: The Next Generation" --out "./data/wiki/st_tng.json"
node wikipedia.js --parent "Star Trek: The Next Generation" --title "Jean-Luc Picard" --out "./data/wiki/st_jeanluc_picard.json"
node wikipedia.js --parent "Star Trek: The Next Generation" --title "Worf" --out "./data/wiki/st_warf.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: Deep Space Nine" --out "./data/wiki/st_ds9.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: Voyager" --out "./data/wiki/st_voy.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: Enterprise" --out "./data/wiki/st_ent.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: Discovery" --out "./data/wiki/st_dicovery.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: Picard" --out "./data/wiki/st_picard.json"
node wikipedia.js --parent "Star Trek" --title "Star Trek: Strange New Worlds" --out "./data/wiki/st_tnw.json"

node wikipedia.js --parent "Franchises" --title "Star Wars" --out "./data/wiki/star_wars.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars: Episode I – The Phantom Menace" --out "./data/wiki/sw_1.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars: Episode II – Attack of the Clones" --out "./data/wiki/sw_2.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars: Episode III – Revenge of the Sith" --out "./data/wiki/sw_3.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars (film)" --rename "Star Wars: Episode IV – A New Hope" --out "./data/wiki/sw_4.json"
node wikipedia.js --parent "Star Wars" --title "The Empire Strikes Back" --rename "Star Wars: Episode V – The Empire Strikes Back" --out "./data/wiki/sw_5.json"
node wikipedia.js --parent "Star Wars" --title "Return of the Jedi" --rename "Star Wars: Episode VI – Return of the Jedi" --out "./data/wiki/sw_6.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars: The Force Awakens" --rename "Star Wars: Episode VII – The Force Awakens" --out "./data/wiki/sw_7.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars: The Last Jedi" --rename "Star Wars: Episode VIII – The Last Jedi" --out "./data/wiki/sw_8.json"
node wikipedia.js --parent "Star Wars" --title "Star Wars: The Rise of Skywalker" --rename "Star Wars: Episode IX – The Rise of Skywalker" --out "./data/wiki/sw_9.json"
node wikipedia.js --parent "Star Wars" --title "Rogue One" --rename "Rogue One: A Star Wars Story" --out "./data/wiki/sw_rogue.json"
node wikipedia.js --parent "Star Wars" --title "Solo: A Star Wars Story" --out "./data/wiki/sw_solo.json"

node wikipedia.js --parent "Franchises" --title "Stargate" --rename "Stargate" --out "./data/wiki/stargate.json"
node wikipedia.js --parent "Stargate" --title "Stargate (film)" --rename "Stargate: The Motion Picture" --out "./data/wiki/sg_film.json"
node wikipedia.js --parent "Stargate" --title "Stargate SG-1" --out "./data/wiki/sg_sg1.json"
node wikipedia.js --parent "Stargate" --title "Stargate Atlantis" --out "./data/wiki/sg_atlantis.json"
node wikipedia.js --parent "Stargate" --title "Stargate Universe" --out "./data/wiki/sg_universe.json"
node wikipedia.js --parent "Stargate" --title "Stargate Origins" --out "./data/wiki/sg_origins.json"
node wikipedia.js --parent "Stargate" --title "Stargate Infinity" --out "./data/wiki/sg_infinity.json"
node wikipedia.js --parent "Stargate" --title "Stargate: The Ark of Truth" --out "./data/wiki/sg_ark.json"
node wikipedia.js --parent "Stargate" --title "Stargate: Continuum" --out "./data/wiki/sg_continum.json"
